# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glassflow < Formula
  desc ""
  homepage "https://www.glassflow.dev/"
  version "1.0.15"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/glassflow/cli/releases/download/v1.0.15/glassflow-cli-1.0.15-darwin-arm64.tar.gz"
      sha256 "80f3007239e212c2bf58d5f54934b58f1466d1bc81f0029a4a6671c3fc55fff7"

      def install
        bin.install "glassflow"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/glassflow/cli/releases/download/v1.0.15/glassflow-cli-1.0.15-darwin-amd64.tar.gz"
      sha256 "dc792fa59155556193be484f61b9218b3f3cf0ab6ef9e8bd2d57dcc1829e2ef8"

      def install
        bin.install "glassflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/glassflow/cli/releases/download/v1.0.15/glassflow-cli-1.0.15-linux-arm64.tar.gz"
      sha256 "751ea2316babd79002c0d341323cc08bfc471519fd59bf895f130dd7b33d814d"

      def install
        bin.install "glassflow"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/glassflow/cli/releases/download/v1.0.15/glassflow-cli-1.0.15-linux-amd64.tar.gz"
      sha256 "87b2a793f3ebd9268cb9671372d2d816d3a9dab6f09630111fbc2c09c3e1ff5c"

      def install
        bin.install "glassflow"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/glassflow/cli/releases/download/v1.0.15/glassflow-cli-1.0.15-linux-armv6.tar.gz"
      sha256 "c96cdcc1bfdc09cb5e312a40f2d1ba9e584e71fed9e6dbb3ef69330dc90d59bf"

      def install
        bin.install "glassflow"
      end
    end
  end
end
