# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. Automation is pending using Github App
class Glassflow < Formula
  desc "GlassFlow CLI for local development environment. Requires Docker (or compatible runtime), kubectl, and helm."
  homepage "https://www.glassflow.dev/"
  version "2.4.3"

  depends_on "helm"
  depends_on "kubectl"

  on_macos do
    on_intel do
      url "https://github.com/glassflow/cli/releases/download/v2.4.3/glassflow-cli-2.4.3-darwin-amd64.tar.gz"
      sha256 "dcc0a8c19b3e71ce8b7b5d54ba74c69113e7d1d25fc6073306d8ae07f8db116b"

      def install
        bin.install "glassflow"
      end
    end
    on_arm do
      url "https://github.com/glassflow/cli/releases/download/v2.4.3/glassflow-cli-2.4.3-darwin-arm64.tar.gz"
      sha256 "2259a8c8f491b6c2452c0d5cc7f79f28b3dcba318d2324692a30f234ccce4e55"

      def install
        bin.install "glassflow"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/glassflow/cli/releases/download/v2.4.3/glassflow-cli-2.4.3-linux-amd64.tar.gz"
        sha256 "9b05f52da43d9bad6b46d15ea580f546e0584f2f75568ac8c630eea471e6650a"

        def install
          bin.install "glassflow"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/glassflow/cli/releases/download/v2.4.3/glassflow-cli-2.4.3-linux-arm64.tar.gz"
        sha256 "2ab442a97b37ba2b05d2288a7ce53002a1617d7641e835978b16b5941d05dcae"

        def install
          bin.install "glassflow"
        end
      end
    end
  end

  test do
    system bin/"glassflow", "--version"
  end
end
